### PR TITLE
Adding absolute path of source directory as prefix to include paths

### PR DESCRIPTION
**Pull request by safayetahmedatge**
Adding absolute path of source directory as prefix to include paths to allow building from arbitrary directory.

### CODE REVIEW

**Comment by flihp** [comment]
Thanks for this @safayetahmedatge. I hadn't done a 'distcheck' build to test out the VPATH stuff on this yet and your first patch here is relevant. I'd prefer to use `$(srcdir)` instead of the absolute variant. I'd also like to squash this into the existing history, likely all the way back into 900a583b8588cfc30a5efcfb5c85ce6ba61323c1. Would that be alright with you?

**Comment by safayetahmedatge** [comment]
@flihp definitely alright with me. Please add this feature how ever you feel is appropriate. I'm including the simulator as a submodule in a larger project and I just needed to place the object files in a separate directory based on the target architecture. I'm not really that familiar with autotools, and my pull-request was just a quick hack after a quick scan of the autotools manual. Thank you for your excellent work.

**Comment by flihp** [comment]
Sorry for the slow action on this @safayetahmedatge. I've just gone back through this branch and added the `$(srcdir)` prefix in the right places. This required rebasing both the `linux-build-libtpm-libplatform-simulator` and `linux-build-libtpm-libplatform` branches. I've also updated the `.travis.yml` file to have the CI builds run the `distcheck` target. This does a VPATH build so that should catch any regressions in VPATH builds.

This was a build thing I was planning to go back and fix after Microsoft merged these patches. That plan got derailed given the current situation over at: https://github.com/Microsoft/ms-tpm-20-ref/pull/8 with the CLA etc. Oh well :man_shrugging:. Till that gets sorted out I guess I'll keep maintaining this stuff.

**Comment by safayetahmedatge** [comment]
Thanks @flihp . Just tested it and everything seems fine. I see what you mean about the CLA situation. That does not look fun. Thank you for maintaining this stuff.

**Pull request closed without merging**
